### ISSUE TITLE
 Invalid command 'RPAF_SetHTTPS'

### ISSUE THREAD

**Issue by matteolavaggi** [gnif/mod_rpaf#58]
apache2 on ubuntu 18.04 does not accept  'RPAF_SetHTTPS' or 'RPAF_SetPORT'

**Comment by deridiot** [comment]
the version in ubuntu - and debian for that matter - is based on 0.6 and not 0.8. the syntax between these versions is different. the old versions used RPAFSetHTTPS instead of RPAF_SetHTTPS

i've stumbled ove the same issue years before as well and was doubting my sanity ;)

either build it yourself or change the syntax to leave out the _ for all of the parameter

**Comment by AndreiG6** [comment]
I don't suggest using it in production either way. See #42

**Comment by matteolavaggi** [comment]
We don't expose Apache direct access to any one. Only nginx can be direct
accessed by client

Il Mer 25 Set 2019, 19:27 Andrei D. <notifications@github.com> ha scritto:

**Comment by AndreiG6** [comment]
It's not about exposing Apache to public view. It's about making sure that if you use KeepAlive in Apache, and you're proxying https (nginx) => http (apache), you will get mixed content issues / busted nginx cache eventually. You have to sacrifice keepalive in order to avoid the bug. Either way, I suggest using @alexat's patch for mod_remoteip from #42 instead. I also got CloudLinux to include it in their apache stack if you use it so no need for custom compile there.

**Comment by matteolavaggi** [comment]
Thanks it's only related to set port and set https right ?

Il Gio 26 Set 2019, 06:28 Andrei D. <notifications@github.com> ha scritto:

**Comment by gnif** [comment]
Closing this issue, this is not the place to discuss support for old versions.
